name: Node.js CI + Sleuth notify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: prod-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test -- --coverage
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage

  notify_sleuth:
    name: Register deploy in Sleuth
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # diagnóstico 401
      - name: Debug Sleuth API (curl)
        env:
          SLEUTH_API_KEY: ${{ secrets.SLEUTH_API_KEY }}
        run: |
          set -e
          curl -i -X POST "https://app.sleuth.io/api/1/deployments/pedro-albuquerque/testepipelines-/register_deploy" \
            -H "Authorization: Bearer $SLEUTH_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"sha":"'"${GITHUB_SHA}"'","environment":"production"}'

      - name: Notify Sleuth
        uses: sleuth-io/sleuth-action@main
        with:
          organization-slug: pedro-albuquerque
          deployment-slug: testepipelines-
          environment: production
          sha: ${{ github.sha }}
          api-key: ${{ secrets.SLEUTH_API_KEY }}
